### ISSUE TITLE
Import failing after update (cannot import name 'scatter_pairwise' from 'pandas_profiling.visualisation.plot')

### ISSUE THREAD

**Issue by MartinVoe** [pandas-profiling/pandas-profiling#378]
**from pandas_profiling import ProfileReport**

fails with error message
_ImportError: cannot import name 'scatter_pairwise' from 'pandas_profiling.visualisation.plot' (C:\Users\UserName\AppData\Local\Continuum\miniconda3\envs\ML\lib\site-packages\pandas_profiling\visualisation\plot.py)_

Python 3.7.1

jupyterlab==1.1.4
pandas==0.25.3
pandas-profiling==2.4.1

**Comment by MartinVoe** [comment]
Fixed after updating jupyterlab to 1.2.6
